name: Reply to new issues with guidelines message

on:
  issue_opened:
    types: [opened]

jobs:
  reply-to-issue:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Reply to issue
        uses: actions/github-script@v6
        with:
          script: |
            github.issues.createComment({
              issue_number: context.payload.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: "Please check the guidelines before submitting an issue: [link to guidelines]"
            })

