name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  build:
    name: Hello new contributor
    runs-on: ubuntu-latest
    steps:
      - uses: actions/first-interaction@v1
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
          issue-message: "Hey, thank you for opening your first Issue ! 🙂 Make sure to follow this guide to getting proper help"
          pr-message: "Hey, thank you for opening your Pull Request !"
