name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest
    steps:
      - name: Comment on issue by current pull request
        uses: alexrogalskiy/github-action-issue-commenter@master
        with:
          message: 'Commenting on issue to testify its valid resolution'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
