name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  comment:
    runs-on: ubuntu-latest

    steps:
    - uses: ben-z/actions-comment-on-issue@1.0.2
      with:
        message: "Gentle reminder:"
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
