name: issue-checklist

on:
  issues:
    types: [opened]

jobs:
  comment_on_new_issue:
    runs-on: ubuntu-latest
    name: Job for commenting on new issue
    steps:
      - name: Comment
        uses: jd-0001/gh-action-comment-on-new-issue@v2.0.3
        with:
          message: "Welcome! please follow the guideline to get help\ntl;dr:\n- update os, qgis, plugin, retry\n- upload zipped instance, results, log"
