name: Create Release

on:
  push:
    tags:
      - 'v[0-9]+.[0-9]+.[0-9]+'

permissions:
  contents: write

jobs:
  build-n-publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: version bump
      run: |
         VERSION=${GITHUB_REF_NAME#v}
         echo "version is ${VERSION}"
         sed -i -e "s/version=0.0.1/version=${VERSION}/" fireanalyticstoolbox/metadata.txt

    - name: download cbc
      uses: robinraju/release-downloader@v1.8
      with:
        repository: "coin-or/Cbc"
        latest: true
        fileName: "*w64-msvc17*.zip"
        out-file-path: "fireanalyticstoolbox/cbc"
        extract: true

    - name: git archive
      run: |
         rm fireanalyticstoolbox/cbc*w64-msvc17*.zip
         git add fireanalyticstoolbox/cbc
         lestash=`git stash create`
         git archive --output "fireanalyticstoolbox_${{ github.ref_name }}.zip" $lestash fireanalyticstoolbox
         # git archive --prefix=fireanalyticstoolbox/ --add-file=fireanalyticstoolbox/metadata.txt \
         #          --prefix=fireanalyticstoolbox/cbc --add-file=fireanalyticstoolbox/cbc/* \
         #          --prefix= --output "fireanalyticstoolbox_${{ github.ref_name }}.zip" HEAD fireanalyticstoolbox

    - name: Create Release
      uses: ncipollo/release-action@v1.12.0
      with:
        artifacts: "fireanalyticstoolbox_${{ github.ref_name }}.zip"
        token: ${{ secrets.GITHUB_TOKEN }}
